import "./any.message";
import "./start.command";
import "./getAdmins.command";
import "./amount.command";
import "./mailing.command";
import "./newAdmin.command";
import "./deleteAdmin.command";
import "./ban.command";
import "./webAppData";
